name: Update IP and DNS

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次

jobs:
  update_ip_and_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 替换为你的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Python script
      env:
        CF_API_EMAIL: ${{ secrets.CF_API_EMAIL }}
        CF_API_KEY: ${{ secrets.CF_API_KEY }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      run: python get_ips.py  # 替换为你的脚本文件名
