name: Update IP List

on:
  #schedule:
  #   - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:
  update_ip_list:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 替换为你需要的Python版本，如3.8、3.9等

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run Python script and update ips.txt
      run: |
        python get_ips.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@users.noreply.github.com'
        git add ips.txt
        git commit -m 'Update IP list on $(date "+%Y/%m/%d %H:%M:%S")'
        git push origin/main
